//
// File generated by rootcint at Sun Nov  7 01:47:57 2010

// Do NOT change. Changes will be lost next time file is generated
//

#include "RConfig.h"
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "hTana_dict.h"

#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"

// START OF SHADOWS

namespace ROOT {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOT
// END OF SHADOWS

namespace ROOT {
   void hTana_ShowMembers(void *obj, TMemberInspector &R__insp, char *R__parent);
   static void hTana_Dictionary();
   static void *new_hTana(void *p = 0);
   static void *newArray_hTana(Long_t size, void *p);
   static void delete_hTana(void *p);
   static void deleteArray_hTana(void *p);
   static void destruct_hTana(void *p);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const ::hTana*)
   {
      ::hTana *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(::hTana),0);
      static ::ROOT::TGenericClassInfo 
         instance("hTana", "hTana.h", 17,
                  typeid(::hTana), DefineBehavior(ptr, ptr),
                  0, &hTana_Dictionary, isa_proxy, 0,
                  sizeof(::hTana) );
      instance.SetNew(&new_hTana);
      instance.SetNewArray(&newArray_hTana);
      instance.SetDelete(&delete_hTana);
      instance.SetDeleteArray(&deleteArray_hTana);
      instance.SetDestructor(&destruct_hTana);
      return &instance;
   }
   TGenericClassInfo *GenerateInitInstance(const ::hTana*)
   {
      return GenerateInitInstanceLocal((::hTana*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::hTana*)0x0); R__UseDummy(_R__UNIQUE_(Init));

   // Dictionary for non-ClassDef classes
   static void hTana_Dictionary() {
      ::ROOT::GenerateInitInstanceLocal((const ::hTana*)0x0)->GetClass();
   }

} // end of namespace ROOT

namespace ROOT {
   // Wrappers around operator new
   static void *new_hTana(void *p) {
      return  p ? ::new((::ROOT::TOperatorNewHelper*)p) ::hTana : new ::hTana;
   }
   static void *newArray_hTana(Long_t nElements, void *p) {
      return p ? ::new((::ROOT::TOperatorNewHelper*)p) ::hTana[nElements] : new ::hTana[nElements];
   }
   // Wrapper around operator delete
   static void delete_hTana(void *p) {
      delete ((::hTana*)p);
   }
   static void deleteArray_hTana(void *p) {
      delete [] ((::hTana*)p);
   }
   static void destruct_hTana(void *p) {
      typedef ::hTana current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOT for class ::hTana

/********************************************************
* hTana_dict.C
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

extern "C" void G__cpp_reset_tagtablehTana_dict();

extern "C" void G__set_cpp_environmenthTana_dict() {
  G__add_compiledheader("TObject.h");
  G__add_compiledheader("TMemberInspector.h");
  G__add_compiledheader("hTana.h");
  G__cpp_reset_tagtablehTana_dict();
}
#include <new>
extern "C" int G__cpp_dllrevhTana_dict() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* hTana */
static int G__hTana_dict_196_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   hTana* p = NULL;
   long gvp = G__getgvp();
   switch (libp->paran) {
   case 1:
     //m: 1
     if ((gvp == G__PVOID) || (gvp == 0)) {
       p = new hTana((TTree*) G__int(libp->para[0]));
     } else {
       p = new((void*) gvp) hTana((TTree*) G__int(libp->para[0]));
     }
     break;
   case 0:
     int n = G__getaryconstruct();
     if (n) {
       if ((gvp == G__PVOID) || (gvp == 0)) {
         p = new hTana[n];
       } else {
         p = new((void*) gvp) hTana[n];
       }
     } else {
       if ((gvp == G__PVOID) || (gvp == 0)) {
         p = new hTana;
       } else {
         p = new((void*) gvp) hTana;
       }
     }
     break;
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   result7->type = 'u';
   result7->tagnum = G__get_linked_tagnum(&G__hTana_dictLN_hTana);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__hTana_dict_196_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((hTana*) G__getstructoffset())->Cut((Long64_t) G__Longlong(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__hTana_dict_196_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((hTana*) G__getstructoffset())->GetEntry((Long64_t) G__Longlong(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__hTana_dict_196_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letLonglong(result7, 110, (G__int64) ((hTana*) G__getstructoffset())->LoadTree((Long64_t) G__Longlong(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__hTana_dict_196_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((hTana*) G__getstructoffset())->Init((TTree*) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__hTana_dict_196_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((hTana*) G__getstructoffset())->Loop();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__hTana_dict_196_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) ((hTana*) G__getstructoffset())->Notify());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__hTana_dict_196_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 1:
      ((hTana*) G__getstructoffset())->Show((Long64_t) G__Longlong(libp->para[0]));
      G__setnull(result7);
      break;
   case 0:
      ((hTana*) G__getstructoffset())->Show();
      G__setnull(result7);
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__hTana_dict_196_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((hTana*) G__getstructoffset())->ana_init((char*) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__hTana_dict_196_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((hTana*) G__getstructoffset())->v2gen((int) G__int(libp->para[0]), (int) G__int(libp->para[1])
, (int) G__int(libp->para[2]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__hTana_dict_196_0_11(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((hTana*) G__getstructoffset())->book_hist((char*) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__hTana_dict_196_0_12(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((hTana*) G__getstructoffset())->ana_end();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__hTana_dict_196_0_13(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   hTana* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new hTana(*(hTana*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   result7->type = 'u';
   result7->tagnum = G__get_linked_tagnum(&G__hTana_dictLN_hTana);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef hTana G__ThTana;
static int G__hTana_dict_196_0_14(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   long gvp = G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 0
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == G__PVOID) {
       delete[] (hTana*) soff;
     } else {
       G__setgvp(G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((hTana*) (soff+(sizeof(hTana)*i)))->~G__ThTana();
       }
       G__setgvp(gvp);
     }
   } else {
     if (gvp == G__PVOID) {
       delete (hTana*) soff;
     } else {
       G__setgvp(G__PVOID);
       ((hTana*) (soff))->~G__ThTana();
       G__setgvp(gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G__hTana_dict_196_0_15(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   hTana* dest = (hTana*) G__getstructoffset();
   *dest = *(hTana*) libp->para[0].ref;
   const hTana& obj = *dest;
   result7->ref = (long) (&obj);
   result7->obj.i = (long) (&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* hTana */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfunchTana_dict {
 public:
  G__Sizep2memfunchTana_dict(): p(&G__Sizep2memfunchTana_dict::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfunchTana_dict::*p)();
};

size_t G__get_sizep2memfunchTana_dict()
{
  G__Sizep2memfunchTana_dict a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritancehTana_dict() {

   /* Setting up class inheritance */
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetablehTana_dict() {

   /* Setting up typedef entry */
   G__search_typename2("Int_t",105,-1,0,-1);
   G__setnewtype(-1,"Signed integer 4 bytes (int)",0);
   G__search_typename2("Bool_t",103,-1,0,-1);
   G__setnewtype(-1,"Boolean (0=false, 1=true) (bool)",0);
   G__search_typename2("Long64_t",110,-1,0,-1);
   G__setnewtype(-1,"Portable signed long integer 8 bytes",0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* hTana */
static void G__setup_memvarhTana(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__hTana_dictLN_hTana));
   { hTana *p; p=(hTana*)0x1000; if (p) { }
   G__memvar_setup((void*)((long)(&p->fChain)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__hTana_dictLN_TTree),-1,-1,1,"fChain=",0,"!pointer to the analyzed TTree or TChain");
   G__memvar_setup((void*)((long)(&p->fCurrent)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"fCurrent=",0,"!current Tree number in a TChain");
   G__memvar_setup((void*)((long)(&p->run)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"run=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->bbcz)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"bbcz=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->centclock)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"centclock=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->rp10)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"rp10=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->rp11)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"rp11=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->rp12)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"rp12=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->bbcQY10)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"bbcQY10=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->bbcQY11)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"bbcQY11=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->bbcQY12)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"bbcQY12=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->bbcQX10)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"bbcQX10=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->bbcQX11)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"bbcQX11=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->bbcQX12)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"bbcQX12=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->nh)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"nh=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->p)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"p[300]=",0,"[nh]");
   G__memvar_setup((void*)((long)(&p->charge)-(long)(p)),115,0,0,-1,G__defined_typename("Short_t"),-1,1,"charge[300]=",0,"[nh]");
   G__memvar_setup((void*)((long)(&p->phi0)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"phi0[300]=",0,"[nh]");
   G__memvar_setup((void*)((long)(&p->the0)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"the0[300]=",0,"[nh]");
   G__memvar_setup((void*)((long)(&p->dcarm)-(long)(p)),115,0,0,-1,G__defined_typename("Short_t"),-1,1,"dcarm[300]=",0,"[nh]");
   G__memvar_setup((void*)((long)(&p->sect)-(long)(p)),115,0,0,-1,G__defined_typename("Short_t"),-1,1,"sect[300]=",0,"[nh]");
   G__memvar_setup((void*)((long)(&p->inemc)-(long)(p)),115,0,0,-1,G__defined_typename("Short_t"),-1,1,"inemc[300]=",0,"[nh]");
   G__memvar_setup((void*)((long)(&p->intof)-(long)(p)),115,0,0,-1,G__defined_typename("Short_t"),-1,1,"intof[300]=",0,"[nh]");
   G__memvar_setup((void*)((long)(&p->isPi)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"isPi[300]=",0,"[nh]");
   G__memvar_setup((void*)((long)(&p->isP)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"isP[300]=",0,"[nh]");
   G__memvar_setup((void*)((long)(&p->isK)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"isK[300]=",0,"[nh]");
   G__memvar_setup((void*)((long)(&p->m2tof)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"m2tof[300]=",0,"[nh]");
   G__memvar_setup((void*)((long)(&p->temc)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"temc[300]=",0,"[nh]");
   G__memvar_setup((void*)((long)(&p->plemc)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"plemc[300]=",0,"[nh]");
   G__memvar_setup((void*)((long)(&p->ecent)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"ecent[300]=",0,"[nh]");
   G__memvar_setup((void*)((long)(&p->twrid)-(long)(p)),115,0,0,-1,G__defined_typename("Short_t"),-1,1,"twrid[300]=",0,"[nh]");
   G__memvar_setup((void*)((long)(&p->n0)-(long)(p)),115,0,0,-1,G__defined_typename("Short_t"),-1,1,"n0[300]=",0,"[nh]");
   G__memvar_setup((void*)((long)(&p->b_run)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__hTana_dictLN_TBranch),-1,-1,1,"b_run=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_bbcz)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__hTana_dictLN_TBranch),-1,-1,1,"b_bbcz=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_centclock)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__hTana_dictLN_TBranch),-1,-1,1,"b_centclock=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_rp10)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__hTana_dictLN_TBranch),-1,-1,1,"b_rp10=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_rp11)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__hTana_dictLN_TBranch),-1,-1,1,"b_rp11=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_rp12)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__hTana_dictLN_TBranch),-1,-1,1,"b_rp12=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_bbcQY10)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__hTana_dictLN_TBranch),-1,-1,1,"b_bbcQY10=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_bbcQY11)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__hTana_dictLN_TBranch),-1,-1,1,"b_bbcQY11=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_bbcQY12)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__hTana_dictLN_TBranch),-1,-1,1,"b_bbcQY12=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_bbcQX10)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__hTana_dictLN_TBranch),-1,-1,1,"b_bbcQX10=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_bbcQX11)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__hTana_dictLN_TBranch),-1,-1,1,"b_bbcQX11=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_bbcQX12)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__hTana_dictLN_TBranch),-1,-1,1,"b_bbcQX12=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_nh)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__hTana_dictLN_TBranch),-1,-1,1,"b_nh=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_p)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__hTana_dictLN_TBranch),-1,-1,1,"b_p=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_charge)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__hTana_dictLN_TBranch),-1,-1,1,"b_charge=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_phi0)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__hTana_dictLN_TBranch),-1,-1,1,"b_phi0=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_the0)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__hTana_dictLN_TBranch),-1,-1,1,"b_the0=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_dcarm)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__hTana_dictLN_TBranch),-1,-1,1,"b_dcarm=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_sect)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__hTana_dictLN_TBranch),-1,-1,1,"b_sect=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_inemc)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__hTana_dictLN_TBranch),-1,-1,1,"b_inemc=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_intof)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__hTana_dictLN_TBranch),-1,-1,1,"b_intof=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_isPi)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__hTana_dictLN_TBranch),-1,-1,1,"b_isPi=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_isP)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__hTana_dictLN_TBranch),-1,-1,1,"b_isP=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_isK)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__hTana_dictLN_TBranch),-1,-1,1,"b_isK=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_m2tof)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__hTana_dictLN_TBranch),-1,-1,1,"b_m2tof=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_temc)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__hTana_dictLN_TBranch),-1,-1,1,"b_temc=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_plemc)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__hTana_dictLN_TBranch),-1,-1,1,"b_plemc=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_ecent)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__hTana_dictLN_TBranch),-1,-1,1,"b_ecent=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_twrid)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__hTana_dictLN_TBranch),-1,-1,1,"b_twrid=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_n0)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__hTana_dictLN_TBranch),-1,-1,1,"b_n0=",0,"!");
   G__memvar_setup((void*)0,108,0,0,-1,-1,-1,4,"G__virtualinfo=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarhTana_dict() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfunchTana(void) {
   /* hTana */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__hTana_dictLN_hTana));
   G__memfunc_setup("hTana",492,G__hTana_dict_196_0_1, 105, G__get_linked_tagnum(&G__hTana_dictLN_hTana), -1, 0, 1, 1, 1, 0, "U 'TTree' - 0 '0' tree", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Cut",300,G__hTana_dict_196_0_2, 105, -1, G__defined_typename("Int_t"), 0, 1, 1, 1, 0, "n - 'Long64_t' 0 - entry", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("GetEntry",818,G__hTana_dict_196_0_3, 105, -1, G__defined_typename("Int_t"), 0, 1, 1, 1, 0, "n - 'Long64_t' 0 - entry", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("LoadTree",784,G__hTana_dict_196_0_4, 110, -1, G__defined_typename("Long64_t"), 0, 1, 1, 1, 0, "n - 'Long64_t' 0 - entry", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Init",404,G__hTana_dict_196_0_5, 121, -1, -1, 0, 1, 1, 1, 0, "U 'TTree' - 0 - tree", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Loop",410,G__hTana_dict_196_0_6, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Notify",633,G__hTana_dict_196_0_7, 103, -1, G__defined_typename("Bool_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Show",417,G__hTana_dict_196_0_8, 121, -1, -1, 0, 1, 1, 1, 0, "n - 'Long64_t' 0 '-1' entry", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ana_init",835,G__hTana_dict_196_0_9, 121, -1, -1, 0, 1, 1, 1, 0, "C - - 0 - outfile", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("v2gen",482,G__hTana_dict_196_0_10, 121, -1, -1, 0, 3, 1, 1, 0, 
"i - - 0 - nevent i - - 0 - mult "
"i - - 0 - dmult", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("book_hist",962,G__hTana_dict_196_0_11, 121, -1, -1, 0, 1, 1, 1, 0, "C - - 0 - outfile", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("ana_end",710,G__hTana_dict_196_0_12, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   // automatic copy constructor
   G__memfunc_setup("hTana", 492, G__hTana_dict_196_0_13, (int) ('i'), G__get_linked_tagnum(&G__hTana_dictLN_hTana), -1, 0, 1, 1, 1, 0, "u 'hTana' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~hTana", 618, G__hTana_dict_196_0_14, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   // automatic assignment operator
   G__memfunc_setup("operator=", 937, G__hTana_dict_196_0_15, (int) ('u'), G__get_linked_tagnum(&G__hTana_dictLN_hTana), -1, 1, 1, 1, 1, 0, "u 'hTana' - 11 - -", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfunchTana_dict() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {
}

static void G__cpp_setup_global2() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalhTana_dict() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
  G__cpp_setup_global2();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funchTana_dict() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__hTana_dictLN_TTree = { "TTree" , 99 , -1 };
G__linked_taginfo G__hTana_dictLN_TBranch = { "TBranch" , 99 , -1 };
G__linked_taginfo G__hTana_dictLN_hTana = { "hTana" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtablehTana_dict() {
  G__hTana_dictLN_TTree.tagnum = -1 ;
  G__hTana_dictLN_TBranch.tagnum = -1 ;
  G__hTana_dictLN_hTana.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtablehTana_dict() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__hTana_dictLN_TTree);
   G__get_linked_tagnum_fwd(&G__hTana_dictLN_TBranch);
   G__tagtable_setup(G__get_linked_tagnum(&G__hTana_dictLN_hTana),sizeof(hTana),-1,1280,(char*)NULL,G__setup_memvarhTana,G__setup_memfunchTana);
}
extern "C" void G__cpp_setuphTana_dict(void) {
  G__check_setup_version(30051515,"G__cpp_setuphTana_dict()");
  G__set_cpp_environmenthTana_dict();
  G__cpp_setup_tagtablehTana_dict();

  G__cpp_setup_inheritancehTana_dict();

  G__cpp_setup_typetablehTana_dict();

  G__cpp_setup_memvarhTana_dict();

  G__cpp_setup_memfunchTana_dict();
  G__cpp_setup_globalhTana_dict();
  G__cpp_setup_funchTana_dict();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfunchTana_dict();
  return;
}
class G__cpp_setup_inithTana_dict {
  public:
    G__cpp_setup_inithTana_dict() { G__add_setup_func("hTana_dict",(G__incsetup)(&G__cpp_setuphTana_dict)); G__call_setup_funcs(); }
   ~G__cpp_setup_inithTana_dict() { G__remove_setup_func("hTana_dict"); }
};
G__cpp_setup_inithTana_dict G__cpp_setup_initializerhTana_dict;

