/********************************************************************
* hTana_dict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error hTana_dict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#include "G__ci.h"
extern "C" {
extern void G__cpp_setup_tagtablehTana_dict();
extern void G__cpp_setup_inheritancehTana_dict();
extern void G__cpp_setup_typetablehTana_dict();
extern void G__cpp_setup_memvarhTana_dict();
extern void G__cpp_setup_globalhTana_dict();
extern void G__cpp_setup_memfunchTana_dict();
extern void G__cpp_setup_funchTana_dict();
extern void G__set_cpp_environmenthTana_dict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "hTana.h"

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__hTana_dictLN_TTree;
extern G__linked_taginfo G__hTana_dictLN_TBranch;
extern G__linked_taginfo G__hTana_dictLN_hTana;

/* STUB derived class for protected member access */
